"""add_fonte_field

Revision ID: a32546c008ea
Revises: 
Create Date: 2026-06-24 16:36:38.575399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a32546c008ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('editais', sa.Column('fonte', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_editais_fonte'), 'editais', ['fonte'], unique=False)
    op.add_column('sync_logs', sa.Column('fonte', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_logs', 'fonte')
    op.drop_index(op.f('ix_editais_fonte'), table_name='editais')
    op.drop_column('editais', 'fonte')
    # ### end Alembic commands ###
